# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-GlassBox-Heavy
version:      0.03
version_from: lib/Test/GlassBox/Heavy.pm
installdirs:  site
requires:
    Devel::LexAlias:               0
    Devel::Symdump:                0
    File::Slurp:                   0
    PadWalker:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
