---
abstract: 'Standalone execution of Perl program subroutines'
author:
  - 'Oliver Gorwits <oliver@cpan.org>'
build_requires:
  Getopt::Long: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Subroutines
requires:
  Devel::LexAlias: 0
  Devel::Symdump: 0
  Exporter: 0
  File::Slurp: 0
  PadWalker: 0
  Symbol: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Test-Subroutines
  homepage: https://github.com/ollyg/Test-Subroutines/wiki
  repository: git://github.com/ollyg/Test-Subroutines.git
version: 1.113280
